//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace HaikanSchoolProjects.passportservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PassportServiceSoap", Namespace="http://www.passport.com/")]
    public partial class PassportService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TokenGetCertOperationCompleted;
        
        private System.Threading.SendOrPostCallback TokenClearOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PassportService() {
            this.Url = global::HaikanSchoolProjects.Properties.Settings.Default.HaikanSchoolProjects_passportservice_PassportService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TokenGetCertCompletedEventHandler TokenGetCertCompleted;
        
        /// <remarks/>
        public event TokenClearCompletedEventHandler TokenClearCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.passport.com/TokenGetCert", RequestNamespace="http://www.passport.com/", ResponseNamespace="http://www.passport.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object TokenGetCert(string token) {
            object[] results = this.Invoke("TokenGetCert", new object[] {
                        token});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void TokenGetCertAsync(string token) {
            this.TokenGetCertAsync(token, null);
        }
        
        /// <remarks/>
        public void TokenGetCertAsync(string token, object userState) {
            if ((this.TokenGetCertOperationCompleted == null)) {
                this.TokenGetCertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTokenGetCertOperationCompleted);
            }
            this.InvokeAsync("TokenGetCert", new object[] {
                        token}, this.TokenGetCertOperationCompleted, userState);
        }
        
        private void OnTokenGetCertOperationCompleted(object arg) {
            if ((this.TokenGetCertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TokenGetCertCompleted(this, new TokenGetCertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.passport.com/TokenClear", RequestNamespace="http://www.passport.com/", ResponseNamespace="http://www.passport.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TokenClear(string token) {
            this.Invoke("TokenClear", new object[] {
                        token});
        }
        
        /// <remarks/>
        public void TokenClearAsync(string token) {
            this.TokenClearAsync(token, null);
        }
        
        /// <remarks/>
        public void TokenClearAsync(string token, object userState) {
            if ((this.TokenClearOperationCompleted == null)) {
                this.TokenClearOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTokenClearOperationCompleted);
            }
            this.InvokeAsync("TokenClear", new object[] {
                        token}, this.TokenClearOperationCompleted, userState);
        }
        
        private void OnTokenClearOperationCompleted(object arg) {
            if ((this.TokenClearCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TokenClearCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void TokenGetCertCompletedEventHandler(object sender, TokenGetCertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TokenGetCertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TokenGetCertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void TokenClearCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591